### ISSUE TITLE
Add FFs with async load support — tracking issue.

### ISSUE THREAD

**Issue by mwkmwkmwk** [YosysHQ/yosys#3028]
Plan:

- [x] Add support for the new capability in `FfData` and all passes that use it — #3027
- [x] Refactor `zinit` to use `FfData` — #3027
- [x] Refactor `simplemap` to use `FfData` — #3029
- [x] Add the actual cell — #3025
- [x] Add the cell to `FfData`, `simplemap`, and some minor passes — #3030
- [x] Add the cell to cxxrtl — #3030
- [x] Add `dfflegalize` support (possibly refactoring it in the process) — #3061
- [x] Actually emit the cell in `proc_dff` — #3031
- [x] Add ECP5 support - #3062
- [ ] Consider recognizing the emulated-via-dffsr pattern in `opt_dff`
